from time import sleep

from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver import ActionChains
from selenium.webdriver.common.actions import interaction
from selenium.webdriver.common.actions.action_builder import ActionBuilder
from selenium.webdriver.common.actions.pointer_input import PointerInput

url = "127.0.0.1:4723/wd/hub"

param = {
  "deviceName": "c6yhprivnbfqw8pz",
  "platformName": "Android",
  "platformVersion": "12",
  # "appPackage": "com.tencent.mobileqq",
  "appPackage": "com.taobao.taobao",
  # "appActivity": "com.tencent.mobileqq.activity.SplashActivity",
  "appActivity": "com.taobao.tao.TBMainActivity",
  "noReset": "true"
}
driver = webdriver.Remote(url, param)
# ### QQ
# driver.implicitly_wait(2)
# el1 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="帐户及设置")
# el1.click()
# el1.click()
# sleep(2)
# el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="编辑资料")
# el2.click()
# sleep(2)
# el3 = driver.find_element(by=AppiumBy.ID, value="com.tencent.mobileqq:id/fzu")
# el3.click()
# sleep(2)
# el4 = driver.find_element(by=AppiumBy.ID, value="com.tencent.mobileqq:id/ivTitleBtnLeft")
# el4.click()
# sleep(2)
# el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="返回按钮")
# el5.click()
# sleep(2)
# el6 = driver.find_element(by=AppiumBy.ID, value="com.tencent.mobileqq:id/ivTitleBtnLeft")
# el6.click()
# actions = ActionChains(driver)
# sleep(2)
# actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
# actions.w3c_actions.pointer_action.move_to_location(862, 1597)
# actions.w3c_actions.pointer_action.pointer_down()
# sleep(2)
# actions.w3c_actions.pointer_action.move_to_location(57, 1563)
# actions.w3c_actions.pointer_action.release()
# actions.perform()


####//淘宝
driver.implicitly_wait(5)
sleep(2)
el8 = driver.find_element_by_xpath("//android.widget.FrameLayout[@content-desc=\"消息\"]/android.widget.ImageView")
el8.click()
sleep(2)
el9 = driver.find_element_by_xpath(
  "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout[1]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.support.v7.widget.RecyclerView/android.widget.FrameLayout[3]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout")
el9.click()
sleep(2)
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(548, 513)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(475, 1823)
sleep(2)
actions.w3c_actions.pointer_action.release()
actions.perform()
sleep(2)
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(536, 682)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(444, 1938)
actions.w3c_actions.pointer_action.release()
sleep(2)
actions.perform()

el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="返回上一页").click()
sleep(2)
el11 = driver.find_element_by_xpath("//android.widget.FrameLayout[@content-desc='购物车']")
el11.click()
sleep(2)
# el12 = driver.find_element("//android.widget.FrameLayout[@content-desc='我的淘宝']/android.widget.ImageView")
# el12.click()
el14 = driver.find_element_by_xpath("//android.widget.FrameLayout[@content-desc=\"我的淘宝\"]/android.widget.ImageView")
el14.click()
sleep(2)
el15 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="设置")
el15.click()
sleep(2)
el16 = driver.find_element_by_xpath(
  "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.RelativeLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.RelativeLayout")
el16.click()
sleep(2)
el17 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="转到上一层级")
el17.click()
sleep(2)
el18 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="转到上一层级")
el18.click()
sleep(2)
el19 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="待收货1")
el19.click()
sleep(2)
el20 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="关闭订单页面")
el20.click()
sleep(2)
el21 = driver.find_element_by_xpath("//android.widget.FrameLayout[@content-desc=\"首页\"]/android.widget.ImageView")
el21.click()
actions = ActionChains(driver)
sleep(2)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(96, 1237)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(892, 1226)
sleep(2)
actions.w3c_actions.pointer_action.release()
sleep(2)
actions.perform()

actions = ActionChains(driver)
sleep(2)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(260, 1429)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(992, 1444)
actions.w3c_actions.pointer_action.release()
sleep(2)
actions.perform()

sleep(2)
actions = ActionChains(driver)
sleep(2)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(8, 1218)
sleep(2)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(739, 1287)
actions.w3c_actions.pointer_action.release()
sleep(2)
actions.perform()

actions = ActionChains(driver)
sleep(2)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(15, 1229)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(839, 1241)
actions.w3c_actions.pointer_action.release()
sleep(2)
actions.perform()
sleep(2)
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(27, 1249)
actions.w3c_actions.pointer_action.pointer_down()
sleep(2)
actions.w3c_actions.pointer_action.move_to_location(980, 1249)
actions.w3c_actions.pointer_action.release()
sleep(2)
actions.perform()

###淘宝
# sleep(5)
# el1 = driver.find_element(by=AppiumBy.CLASS_NAME, value="//android.widget.FrameLayout[@content-desc='购物车']/android.widget.ImageView").click()
# sleep(8)
# el2 = driver.find_element(by=AppiumBy.CLASS_NAME, value="//android.widget.FrameLayout[@content-desc='我的淘宝']/android.widget.ImageView").click()
# sleep(2)
# el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="设置")
# el3.click()
# sleep(2)
# el4 = driver.find_element(by=AppiumBy.CLASS_NAME, value="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.RelativeLayout/android.support.v7.widget.RecyclerView/android.widget.FrameLayout[1]/android.widget.RelativeLayout")
# el4.click()

# if __name__=="__main__":
